"""add_folder_structure_ids_to_admin

Revision ID: 59d71681e084
Revises: 26ca7dbacc24
Create Date: 2025-12-10 22:46:45.096546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59d71681e084'
down_revision = '26ca7dbacc24'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('folder_pendientes_id', sa.String(), nullable=True))
    op.add_column('admins', sa.Column('folder_en_revision_id', sa.String(), nullable=True))
    op.add_column('admins', sa.Column('folder_aprobados_id', sa.String(), nullable=True))
    op.add_column('admins', sa.Column('folder_rechazados_id', sa.String(), nullable=True))
    op.add_column('admins', sa.Column('folder_archivados_id', sa.String(), nullable=True))
    op.drop_index('ix_admins_user_id', table_name='admins')
    op.create_unique_constraint(None, 'admins', ['user_id'])
    op.drop_constraint('fk_admins_user_id_users', 'admins', type_='foreignkey')
    op.create_foreign_key(None, 'admins', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admins', type_='foreignkey')
    op.create_foreign_key('fk_admins_user_id_users', 'admins', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'admins', type_='unique')
    op.create_index('ix_admins_user_id', 'admins', ['user_id'], unique=True)
    op.drop_column('admins', 'folder_archivados_id')
    op.drop_column('admins', 'folder_rechazados_id')
    op.drop_column('admins', 'folder_aprobados_id')
    op.drop_column('admins', 'folder_en_revision_id')
    op.drop_column('admins', 'folder_pendientes_id')
    # ### end Alembic commands ###
